### PR TITLE
Fix bounding box errors

### PR DESCRIPTION
**Pull request by rlm1023**

### CODE REVIEW

**Comment by rlm1023** [comment]
I don't really know how you'd test this bug. It looks like there are tests in the spec that should have caught this bug, but I probably don't know enough about how filters work and interact with ui-select to speak intelligently on them.

**Review by lameyer — COMMENTED** [review]
This looks good 👍 

I think/hope that we can write a test for this similar to the other append dropdown to body tests like this one:

https://github.com/looker/ui-select/blob/990565d632edd7107bdde3d156fc000d5154bbac/test/select.spec.js#L3546-L3553

So we can set up the dropdown and open it in the test. The reason these tests aren't erroring now could be because of the timeout in `calculateDropdownPosAfterAnimation`. So maybe if you do a `$timeout.flush()` or something similar in the tests, you could find a case where this errors before your fix? I'm not positive this will work, but it's a good place to start.

Let me know if there's anything I can help with!

**Comment by rlm1023** [comment]
So I spent most of yesterday trying to write a test to catch this, but to no avail. Given that it was somewhat tricky to reproduce the problem in the app, I think writing a test is going to be more difficult than it's worth. Going to merge this.

**Comment by lameyer** [comment]
That works for me 👍 Thank you for taking a look!

**Pull request merged**
